version: '3.8'
services:
  bein_stream_dev:
    image: bein_stream_dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: "nest start --watch"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist/
      - /usr/src/app/node_modules/
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - bein-stream-network
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
      - ./data/log:/logs:z
      - ./data/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 4G
    networks:
      - bein-stream-network
  redis:
    image: redis/redis-stack
    container_name: redis_feed
    restart: always
    env_file:
      - ./.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT_NUMBER: ${REDIS_PORT}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - bein-stream-network

networks:
  bein-stream-network:
    name: bein-stream