version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
      - ./data/log:/logs:z
      - ./data/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 4G
    networks:
      - bein-stream-network

networks:
  bein-stream-network:
    name: bein-stream