version: '3.8'
services:
  bein_stream_dev:
    image: bein_stream_dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: "nest start --watch"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist/
      - /usr/src/app/node_modules/
    ports:
      - 3001:3001
    networks:
      - bein-stream-network
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - bein-feed-network
  redis:
    image: bitnami/redis:latest
    container_name: redis_feed
    env_file:
      - ./.env
    environment:
      REDIS_PASSWORD: 123456
      REDIS_PORT_NUMBER: 6376
    ports:
      - '6376:6376'
    networks:
      - bein-feed-network

networks:
  bein-stream-network:
    name: bein-stream
