receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:


exporters:
  logging:
    loglevel: debug
  otlp/elastic:
  # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "http://apm-server:8200"
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]