export const USER_HTTP_TOKEN = 'USER_HTTP_TOKEN';
export const GROUP_HTTP_TOKEN = 'GROUP_HTTP_TOKEN';
export const MEDIA_HTTP_TOKEN = 'MEDIA_HTTP_TOKEN';
export const LAMBDA_COUNT_TOKEN_HTTP_TOKEN = 'LAMBDA_COUNT_TOKEN_HTTP_TOKEN';
export const NOTIFICATION_HTTP_TOKEN = 'NOTIFICATION_HTTP_TOKEN';
