import {
  LibPostCategoryRepository,
  LibPostGroupRepository,
  LibPostSeriesRepository,
  LibPostTagRepository,
  LibQuizAnswerRepository,
  LibQuizQuestionRepository,
  LibUserMarkReadPostRepository,
  LibUserReportContentRepository,
  LibUserSavePostRepository,
  LibUserSeenPostRepository,
  LibContentRepository,
  LibQuizParticipantAnswerRepository,
  LibQuizParticipantRepository,
  LibQuizRepository,
  LibCommentReactionRepository,
  LibPostReactionRepository,
  LibReactionCommentDetailsRepository,
  LibReactionContentDetailsRepository,
} from '@libs/database/postgres/repository';

export const libRepositoryProvider = [
  LibCommentReactionRepository,
  LibContentRepository,
  LibPostCategoryRepository,
  LibPostGroupRepository,
  LibPostReactionRepository,
  LibPostSeriesRepository,
  LibPostTagRepository,
  LibQuizAnswerRepository,
  LibQuizParticipantAnswerRepository,
  LibQuizParticipantRepository,
  LibQuizQuestionRepository,
  LibQuizRepository,
  LibReactionCommentDetailsRepository,
  LibReactionContentDetailsRepository,
  LibUserMarkReadPostRepository,
  LibUserReportContentRepository,
  LibUserSavePostRepository,
  LibUserSeenPostRepository,
];
