version: 2.1
parameters:
  run_workflow_sbx:
    default: true
    type: boolean

  run_workflow_stg:
    default: true
    type: boolean

  run_workflow_pro:
    default: true
    type: boolean

jobs:
  sbx:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: beingroup/bein-stream-backend-api-sbx
      BASE: bein-base
      ENVIRONMENT_BASE: bein-sandbox-base
      LIVE: bein-sandbox-live-stream
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Pull Kustomize resources
          command: |
            mkdir ~/app/$BASE
            cd ~/app/$BASE
            git clone -b $BASE git@bitbucket.org:bein-platform/bic-kube.git
            cp -r bic-kube/* .
            rm -rf bic-kube

            mkdir ~/app/$ENVIRONMENT_BASE
            cd ~/app/$ENVIRONMENT_BASE
            git clone -b $ENVIRONMENT_BASE git@bitbucket.org:bein-platform/bic-kube.git
            cp -r bic-kube/* .
            rm -rf bic-kube

            mkdir ~/app/$LIVE
            cd ~/app/$LIVE
            git clone -b $LIVE git@bitbucket.org:bein-platform/bic-kube.git
            cp -r bic-kube/* .
            rm -rf bic-kube
      - run:
          name: Run Kustomize
          command: |
            cd ~/app/$LIVE
            ~/app/kubectl kustomize ./ > ~/app/result.yaml
      - run:
          name: Deploy Code
          command: |
            chmod +x ./$BASE/ci-deploy.sh
            ./$BASE/ci-deploy.sh
      - run:
          name: View live configuration
          command: |
            cat ~/app/result.yaml
  stg:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: beingroup/bein-stream-backend-api-stg
      BASE: bein-base
      ENVIRONMENT_BASE: bein-staging-base
      LIVE: bein-staging-live-stream
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Pull Kustomize resources
          command: |
            mkdir ~/app/$BASE
            cd ~/app/$BASE
            git clone -b $BASE git@bitbucket.org:bein-platform/bic-kube.git
            cp -r bic-kube/* .
            rm -rf bic-kube

            mkdir ~/app/$ENVIRONMENT_BASE
            cd ~/app/$ENVIRONMENT_BASE
            git clone -b $ENVIRONMENT_BASE git@bitbucket.org:bein-platform/bic-kube.git
            cp -r bic-kube/* .
            rm -rf bic-kube

            mkdir ~/app/$LIVE
            cd ~/app/$LIVE
            git clone -b $LIVE git@bitbucket.org:bein-platform/bic-kube.git
            cp -r bic-kube/* .
            rm -rf bic-kube
      - run:
          name: Run Kustomize
          command: |
            cd ~/app/$LIVE
            ~/app/kubectl kustomize ./ > ~/app/result.yaml
      - run:
          name: Deploy Code
          command: |
            chmod +x ./$BASE/ci-deploy.sh
            ./$BASE/ci-deploy.sh
      - run:
          name: View live configuration
          command: |
            cat ~/app/result.yaml
  pro:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: beingroup/bein-stream-backend-api-pro
      BASE: bein-base
      ENVIRONMENT_BASE: bein-production-base
      LIVE: bein-production-live-stream
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Pull Kustomize resources
          command: |
            mkdir ~/app/$BASE
            cd ~/app/$BASE
            git clone -b $BASE git@bitbucket.org:bein-platform/bic-kube.git
            cp -r bic-kube/* .
            rm -rf bic-kube

            mkdir ~/app/$ENVIRONMENT_BASE
            cd ~/app/$ENVIRONMENT_BASE
            git clone -b $ENVIRONMENT_BASE git@bitbucket.org:bein-platform/bic-kube.git
            cp -r bic-kube/* .
            rm -rf bic-kube

            mkdir ~/app/$LIVE
            cd ~/app/$LIVE
            git clone -b $LIVE git@bitbucket.org:bein-platform/bic-kube.git
            cp -r bic-kube/* .
            rm -rf bic-kube
      - run:
          name: Run Kustomize
          command: |
            cd ~/app/$LIVE
            ~/app/kubectl kustomize ./ > ~/app/result.yaml
      - run:
          name: Deploy Code
          command: |
            chmod +x ./$BASE/ci-deploy.sh
            ./$BASE/ci-deploy.sh
      - run:
          name: View live configuration
          command: |
            cat ~/app/result.yaml

workflows:
  version: 2
  Sandbox:
    when: << pipeline.parameters.run_workflow_sbx >>
    jobs:
      - sbx:
          filters:
            branches:
              only: sandbox
          context:
            - bein-backend-general
            - bein-backend-sbx

  Staging:
    when: << pipeline.parameters.run_workflow_stg >>
    jobs:
      - stg:
          filters:
            branches:
              only: staging
          context:
            - bein-backend-general
            - bein-backend-stg

  Production:
    when: << pipeline.parameters.run_workflow_pro >>
    jobs:
      - pro:
          filters:
            branches:
              only: master
          context:
            - bein-backend-general
            - bein-backend-pro