apiVersion: v1
kind: Service
metadata:
  name: bein-stream-backend-api
  namespace: default
  labels:
    app: bein-stream-backend-api
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: http
      name: http
  selector:
    app: bein-stream-backend-api
