export const RULES = {
  LIMIT_ATTACHED_SERIES: 3,
  TAG_MAX_NAME: 32,
  QUIZ_TITLE_MAX_LENGTH: 65,
  QUIZ_DESCRIPTION_MAX_LENGTH: 255,
  QUIZ_MAX_QUESTION: 50,
  QUIZ_MAX_ANSWER: 6,
  QUIZ_TIME_LIMIT_DEFAULT: 30 * 60,
};
