import { QueueName } from '@libs/infra/v2-queue';

import {
  CONTENT_SCHEDULED_PROCESSOR_TOKEN,
  CONTENT_SCHEDULED_WORKER_TOKEN,
  QUIZ_PARTICIPANT_PROCESSOR_TOKEN,
  QUIZ_PARTICIPANT_WORKER_TOKEN,
  QUIZ_PENDING_PROCESSOR_TOKEN,
  QUIZ_PENDING_WORKER_TOKEN,
} from '../provider';

import { WorkerConstants } from './types';

export const WORKER_ADAPTER_SERVICES: WorkerConstants[] = [
  {
    QUEUE_NAME: QueueName.CONTENT_SCHEDULED,
    WORKER_TOKEN: CONTENT_SCHEDULED_WORKER_TOKEN,
    PROCESSOR_TOKEN: CONTENT_SCHEDULED_PROCESSOR_TOKEN,
    GROUP_CONCURRENCY: {
      concurrency: parseInt(process.env.CONTENT_SCHEDULED_GROUP_CONCURRENCY) | 2,
    },
    CONCURRENCY: parseInt(process.env.CONTENT_SCHEDULED_CONCURRENCY) | 5,
  },
  {
    QUEUE_NAME: QueueName.QUIZ_PENDING,
    WORKER_TOKEN: QUIZ_PENDING_WORKER_TOKEN,
    PROCESSOR_TOKEN: QUIZ_PENDING_PROCESSOR_TOKEN,
    GROUP_CONCURRENCY: {
      /**
       * @note OpenAI limitation
       */
      limit: {
        max: 3,
        duration: 1000,
      },
    },
    CONCURRENCY: parseInt(process.env.QUIZ_PENDING_CONCURRENCY) | 1,
  },
  {
    QUEUE_NAME: QueueName.QUIZ_PARTICIPANT_RESULT,
    WORKER_TOKEN: QUIZ_PARTICIPANT_WORKER_TOKEN,
    PROCESSOR_TOKEN: QUIZ_PARTICIPANT_PROCESSOR_TOKEN,
    GROUP_CONCURRENCY: {
      concurrency: parseInt(process.env.QUIZ_PARTICIPANT_GROUP_CONCURRENCY) | 1,
    },
    CONCURRENCY: parseInt(process.env.QUIZ_PARTICIPANT_CONCURRENCY) | 5,
  },
];
