import jwkToPem from 'jwk-to-pem';
import * as jwt from 'jsonwebtoken';
import { lastValueFrom } from 'rxjs';
import { HttpService } from '@nestjs/axios';
import { ConfigService } from '@nestjs/config';
import { ICognitoConfig } from '../../config/cognito';
import { TokenExpiredError } from 'jsonwebtoken';
import { Inject, Injectable, Logger, UnauthorizedException } from '@nestjs/common';
import { ClassTransformer } from 'class-transformer';
import { LogicException } from '../../common/exceptions';
import { HTTP_STATUS_ID } from '../../common/constants';
import { IUserApplicationService, USER_APPLICATION_TOKEN, UserDto } from '../v2-user/application';
import { IAppConfig } from '../../config/app';

@Injectable()
export class AuthService {
  private _logger = new Logger(AuthService.name);
  private _classTransformer = new ClassTransformer();

  public constructor(
    @Inject(USER_APPLICATION_TOKEN)
    private _userAppService: IUserApplicationService,
    private _httpService: HttpService,
    private _configService: ConfigService
  ) {}

  public async getUser(payload: Record<string, any>): Promise<UserDto> {
    const user = {
      email: payload['email'],
      username: payload['cognito:username'],
    };

    const appConfig = this._configService.get<IAppConfig>('app');
    let userInfo;
    if (appConfig.env === 'local') {
      userInfo = {
        fullname: 'Ngoc Linh',
        id: '6235bc91-2255-4f4b-bcfa-bebcd24e27ac',
        username: 'ngocanh170',
        email: 'ngocanh170@mailinator.com',
        avatar:
          'https://bic-dev-entity-attribute-s3-bucket.s3.ap-southeast-1.amazonaws.com/static/user/default-avatar.png',
        groups: [
          '0711594f-733e-48b9-8e33-8a02e3361fc1',
          'e2487d02-b7be-4185-8245-f7596eba1437',
          'fe3ce252-cd03-41b6-aa8a-ea27ab7a26aa',
          '786bc80c-750c-4393-acc4-5918c0af0992',
          '928d15c3-8225-4197-8189-63907f17093d',
          '7d75f22f-6be0-4ac0-aa5c-07bd88c46595',
          '83cd9966-83d7-4fd3-bcc4-e64b2ca4ad63',
          '3ba381b0-e718-4395-91b9-ff5d6a104845',
          'b2f9eae5-d93f-45ed-b2c3-bb46911ffd40',
          'aea46e6d-f145-459a-8fc1-830ba2d7e0f9',
          '35b5fb8f-6f7a-4ac2-90bb-18199096c429',
          '91830f8b-3ab1-4899-8811-c4d18af457b5',
          '1fc06290-9a3c-4726-9615-174dbc8ff5d9',
        ],
        permissions: {
          communities: {
            'e32a2676-0fbe-4900-a00d-e2825329b24e': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '41535749-b770-4042-9933-f41dd07d072e': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '0fe6cb6d-a9ab-4127-9ed2-f85c9302140e': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '5870fef3-9dd2-4127-85cf-b08e7379f088': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'crud_uc',
            ],
            'b855ffbf-860b-4467-805d-b7b1be3f4603': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'd78559b8-3df7-4b7e-a839-15ad1e2dc2f1': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '0131c77c-0b52-45ff-933d-49932f431134': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '7cd8c3fb-3cd0-4e7f-9775-788ac94edb27': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '406b5420-7a1c-4bba-8e3b-315b857a9eaf': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '072b2bdc-170f-4b3d-b1fb-6cf85ef4d360': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'ce58beb6-6b0d-414b-ab0b-a5f37bebe68f': [
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_post_article',
              'crud_series',
              'publish_unpublish_post',
              'crud_uc',
              'cud_tags',
            ],
            '5d29da0f-80b7-4359-8a32-aa8a219c7b8b': [
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
            ],
            'b5c7a117-dcb8-47ba-9677-dc33da0320ba': ['manage'],
            '1c060f8a-7273-4d99-be69-713e2ae82d45': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '4a26b1b0-84e3-4656-9963-839ce0a0ea33': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '9cc1e9b4-cd7c-48b4-bc00-ed3950a413cb': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '1bdfd1aa-955f-46f3-82cf-4ee2ff293cae': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '10bc9ac0-c9af-4e79-8f59-d7c54a499bc1': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'c4b428fc-5d6e-4241-a9a5-3f71f09c53d2': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '5d27c61d-2bc0-4a6c-a8e2-b024f9b846c6': ['manage'],
            '76ba1664-b2b4-475b-90f0-5a21634cd263': [
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_post_article',
              'crud_series',
              'publish_unpublish_post',
              'crud_uc',
              'cud_tags',
            ],
            '2990add4-6045-4ab4-98b1-27a3636388d0': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '99540b1e-eda7-467f-90ca-ee7419428b04': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '7cb5d8e2-f8f4-4753-9ead-8ce50fc290ea': [
              'channel_mentions',
              'delete_own_message',
              'edit_own_message',
              'send_message',
              'crud_post_article',
              'approve_reject_jr',
              'crud_uc',
            ],
            '15337361-1577-4b7b-a31d-990df06aa446': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'edit_post_setting',
            ],
            'c84d4d4c-9995-430a-a7b1-8de0647379aa': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '4e6efb68-c6d2-4fe4-abad-7e91c7b93e9d': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '5332be8b-5eb8-41de-92d9-ccdcecf4979e': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '4fee270a-074a-48b3-a988-7f009418d93f': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'crud_uc',
            ],
            'b0b8a5ea-aa7c-4463-82b8-a380ec8ecbc2': ['crud_uc'],
            '0204fff4-1269-4213-a1a6-4d60be69af0d': [
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_post_article',
              'crud_series',
              'publish_unpublish_post',
              'crud_uc',
              'cud_tags',
            ],
            'ba79c0f8-45fb-4a94-b4ac-b50516d8c09e': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'fb613ef8-58f4-49ac-834f-c01b1b0fe0c1': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '7ea8197a-4eef-4ecc-a389-4b211f6a4e1e': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'e5a191a9-2867-4656-b011-71b186174de6': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '79421f85-62a2-47ac-889d-734451f9ee98': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '750fff94-beee-4edd-b064-4c6b692d9f4c': [
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_post_article',
              'crud_series',
              'publish_unpublish_post',
              'crud_uc',
              'cud_tags',
            ],
            '008cadb9-1e73-4783-8bac-5913562ff2a0': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '64e505e6-7707-4109-b405-a18ae0340c84': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'eabaf024-f1e5-428c-be0e-71d40efd1166': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'crud_series',
              'edit_post_setting',
            ],
            '511189b7-859e-4efd-b6f2-bc9f7c248f7c': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '613b3ccf-37df-45a3-9f3c-5250ed0d04a2': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '6ffc4d4e-5754-4d8d-ad67-a590c0bb91e6': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '4fcc7ec2-c415-4121-b966-9deb97eb6956': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '03ad6513-3c1d-4c87-b7da-c282321d5c67': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '67855058-92f6-4e56-8833-a6e60dd0f8ea': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '905d92cc-ff08-492e-a00a-892403a7988a': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '9bc01929-ca69-4579-9a70-af3c5fc89ea6': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '3091f7a4-977b-461f-a4d4-f7b87364fee4': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '806957d4-cde3-432b-bc22-fdc476b82147': [
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_post_article',
              'crud_series',
              'publish_unpublish_post',
              'crud_uc',
              'cud_tags',
            ],
            '041f68fd-14de-4bdd-92fc-dfb78cfdb95a': [
              'channel_mentions',
              'crud_post_article',
              'delete_own_message',
              'edit_own_message',
              'crud_uc',
            ],
            '25f9d2e2-e8d2-4a71-9cb6-ed7ff0e1a6f4': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '153c02e4-3b08-4c3e-bb74-dd2d94d0a5e7': ['manage'],
            'ee2eb768-072d-449d-97cb-0bfeb8195565': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '4226ab3a-5dca-4172-abcc-526a3602b9e8': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '888b8b28-187d-4242-bf53-b36297f06872': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '2221d481-9412-4744-97b7-6550e10a9b23': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'bd98bd0b-ed10-4a2c-9c58-f60f9c571c7b': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '94fc1470-bb72-4f16-9bd6-0c0444a960a0': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'f1b002dc-37dd-41ab-9b50-5963207c1439': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'bd542bff-a95b-4c71-94d9-61020ebd9f4e': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'be49b479-47ab-464a-b316-7bd3af7459a7': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '1b89f073-21a8-4522-81b1-61ac0d29058d': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'ad402e05-9de2-423c-9266-4f940bf6a59f': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '91a70890-3431-4cc3-a388-be2f3cd68acd': [
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_post_article',
              'crud_series',
              'publish_unpublish_post',
              'crud_uc',
              'cud_tags',
            ],
            'd4cf7298-c8c2-4129-b19e-853381c0c0ef': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '656cebfe-1b91-473f-97fd-96837bf9e2a5': [
              'add_member',
              'approve_reject_jr',
              'archive_groups',
              'assign_content_owner',
              'assign_unassign_role',
              'channel_mentions',
              'create_custom_emoji',
              'create_inner_groups',
              'crud_post_article',
              'crud_series',
              'crud_uc',
              'delete_inner_groups',
              'delete_others_message',
              'delete_own_message',
              'edit_info',
              'edit_join_setting',
              'edit_own_message',
              'edit_post_approval_setting',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'edit_privacy',
              'invite_member',
              'order_move_group_structure',
              'publish_unpublish_post',
              'remove_member',
              'send_message',
              'cud_tags',
            ],
            '14a28f07-c074-470c-a0ba-d8e9664492f6': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'b3942f79-d4d0-4b0f-afe2-02cbfe726632': [
              'crud_post_article',
              'crud_uc',
              'delete_own_message',
              'edit_own_message',
              'send_message',
            ],
            '5892fe0b-9574-41c1-a64d-558c97b9260f': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '31d78092-81aa-4797-8cc5-d28d15a1c6d4': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'badcb7ae-85ea-4b2f-8983-065f974c2426': [
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_post_article',
              'crud_series',
              'publish_unpublish_post',
              'crud_uc',
              'cud_tags',
            ],
            'd3ed5f00-a079-4642-8c33-8ed362ec7ef4': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '788a7fc2-6e06-4d02-bb64-e6766ba7ce97': ['manage'],
          },
          groups: {
            '2c4bb803-8b87-4ff5-aa24-d28f1c959466': ['crud_uc'],
            '09562521-eba0-42e7-bf01-1c9414955195': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'd84a0771-699d-4ccc-b5f5-5b308d4ba14b': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '06850d48-f2c4-44a2-a96c-9828b3fe2fae': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'crud_series',
              'edit_post_setting',
            ],
            '818bd511-aa2e-4fb5-9973-c227e0ef3cc0': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '868ae713-6365-43bd-85ef-cdc2c21eca9b': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'crud_uc',
            ],
            'f7bbd199-219b-49cf-abbc-c0d3ebe056be': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '3aa98859-0c1a-4156-9461-221b405055d3': [
              'channel_mentions',
              'crud_post_article',
              'delete_own_message',
              'edit_own_message',
              'crud_uc',
            ],
            'a29bfb75-4d07-4f7c-9bb1-e1fdffead4ec': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            '40c2d49d-20eb-462d-93de-67c29ea33fbc': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'cud_tags',
            ],
            'e5aec0a8-e661-48fa-957a-900de7d6e0eb': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '215a4c13-d3d2-44f4-9bdc-4fa28b1949c9': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_series',
              'publish_unpublish_post',
              'cud_tags',
            ],
            '21e9d470-0217-4091-80b3-fe473f79d320': [
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
            ],
            '3433175b-b15c-4d2f-a63e-cb97a95c6aa2': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '86616a93-2353-4f30-af69-53fc14c48a91': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            'b206a8f7-1062-49fa-a02d-2334da71a7ae': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '82df17b0-4b57-400a-8bfa-e8ac7d27f529': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            '556779ef-92f4-4b4a-b161-76a811941032': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '90d650e8-68bc-4c1b-aa2c-c5d93be428f5': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '8f53339e-e8fd-4d70-a14a-32e64d870afe': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            '30453587-5c02-40fb-94df-6d9fd926df41': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'manage',
            ],
            '4c1b4093-a664-4a25-b40e-8dd29a8a6b93': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            'ece52a62-6158-4cae-9ccd-a7b4bcc12c97': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'manage',
            ],
            '51fbf70d-a8c9-4a4a-b5d9-2b83459c3265': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'e22e09b2-7956-483a-ab46-87db8a74c09d': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_series',
              'publish_unpublish_post',
              'cud_tags',
            ],
            'c31ea523-002c-4821-90c4-01ece5d63025': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '3f2077f0-5ebd-45d4-b757-62327de2d713': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            'fb17f160-de22-404d-be70-1414c4a229ed': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '7d5a7033-5d78-40cc-8ab7-540580a844b0': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            'c983c7e3-c87f-4cda-80ce-61f537c89dd3': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '047b81a9-c7e3-4c7c-98a4-ccb4f6eb37ef': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            '57defe75-dd8d-49fe-8a1c-65297b01757d': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '77bbcead-6ff6-4a92-af6c-afd2c1f6f429': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'c8cf048f-c291-4041-af92-1b6af0ef74f4': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'f65af92c-b78e-4519-b195-7654139ae992': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '346e076f-3762-4ad6-bd80-8f84b374cb55': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'bd3e8a34-d642-4aee-a13e-30d1b1fdaa1b': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '1d43514e-6a80-4912-8a53-c308063bb756': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '4739cf1c-44f9-4d66-adad-c97abc94632c': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_series',
              'publish_unpublish_post',
              'cud_tags',
            ],
            'e3dd8f2e-fea4-4a36-ad2c-9514c6b0db05': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'd3d5c620-98b7-4b28-94ef-0395c27203f9': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '949ee208-162e-4990-ae81-ffa7916b386f': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'cba9e60b-0ca4-422c-9196-ef452ae44e22': [
              'channel_mentions',
              'delete_own_message',
              'edit_own_message',
              'send_message',
              'crud_post_article',
              'approve_reject_jr',
              'crud_uc',
            ],
            '32b1cdda-ae64-4836-ac4e-0263a4828a30': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'fe3ce252-cd03-41b6-aa8a-ea27ab7a26aa': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'd2ea57cc-f7e0-4d4f-be99-1d9d00d68b05': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'ca20d746-3d03-48fb-a012-bac3fc4fd64a': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '8f914eaa-821f-44b8-80e0-7bac69346397': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '874887fe-6d1d-449d-936a-f89b104118c0': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '0f5c4bb8-323b-41ee-8aed-b064fecf492b': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'c4d8ce76-b229-4679-9172-23c7ed217271': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '1fc06290-9a3c-4726-9615-174dbc8ff5d9': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_series',
              'publish_unpublish_post',
              'cud_tags',
            ],
            'c5a0cbc6-3716-4450-97c0-6d61093298b1': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '2b15df32-ac56-47d8-ac63-aaa2dd199d00': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'a2878812-95df-4810-b036-9967de528e6e': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '85b2e8e6-9488-4bcf-8821-0d3dcffe6550': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'b01fb58e-9299-4a0e-a55f-9839293fb42a': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'manage',
            ],
            'a15c0db5-ce1e-430f-8a98-49822a0f502e': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            'b7b32c28-f032-4684-baee-5f042408e7b6': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'ab551d44-7de3-4b33-8f14-7392d548b58c': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'manage',
            ],
            'd69fe241-b911-49d5-a986-a24fca816797': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '1cd3bdfe-f9aa-4a40-a644-557e21c04248': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '52b8bb70-c091-4e71-af7e-3102aa515c92': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '7f90d645-ea62-41f7-93cb-595e38d750ae': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '2d9fcec7-3a70-4951-8269-67f89d1cd97c': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            '1a80fc4d-7aa7-4e2d-8858-d1dabdb8e09e': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'cud_tags',
              'manage',
            ],
            '93586a89-6f4e-470e-ac37-42132f147552': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            'b1da0659-adde-4800-a309-89ab945832b2': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            '10b3cfe3-21c0-4f75-9542-e00641745280': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            'b1cf8345-0338-44bf-9d1c-a3421e6f53a2': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            'dd77d68f-3a6c-4fa7-b873-3c37ed788861': [
              'crud_post_article',
              'crud_uc',
              'delete_own_message',
              'edit_own_message',
              'send_message',
              'add_member',
              'approve_reject_jr',
              'archive_groups',
              'assign_content_owner',
              'assign_unassign_role',
              'channel_mentions',
              'create_custom_emoji',
              'create_inner_groups',
              'crud_series',
              'delete_inner_groups',
              'delete_others_message',
              'edit_info',
              'edit_join_setting',
              'edit_post_approval_setting',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'edit_privacy',
              'invite_member',
              'order_move_group_structure',
              'publish_unpublish_post',
              'remove_member',
              'cud_tags',
            ],
            '8fab734a-7f47-42e0-97e5-fad886970b66': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'manage',
            ],
            '9a0f69c8-2f0c-408f-9658-8c5eced86aa9': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'cud_tags',
              'crud_custom_scheme',
              'create_custom_emoji',
              'assign_content_owner',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
            ],
            '91830f8b-3ab1-4899-8811-c4d18af457b5': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_series',
              'publish_unpublish_post',
              'cud_tags',
            ],
            '3dfc8748-f625-4f4d-a1bc-f958cc131994': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            'd9dfec89-a3b3-44b0-a464-64a807518ac1': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            'f4472c56-08a9-4612-b9b0-5fe3f25167b5': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'edit_info',
              'cud_tags',
              'manage',
            ],
            '354c5bca-8b57-4c21-9442-f250c1cc6d6d': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '896e4e71-21eb-4f4e-9916-c026c0f5c699': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '9bd67c2b-8f79-4e00-8acc-86a450b230a7': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '6b3c2ccc-bb12-4022-9c4d-7ad85bf6c766': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'a51a566d-b47a-4924-ad62-6bc6162c805e': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '4f2a225d-78cd-4cdc-89d9-2f8369e99629': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '9d402f73-1891-4a17-b3cf-9a69c34e9e04': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '57f23f5c-b995-461b-afb5-5702688257c6': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'crud_custom_scheme',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'create_custom_emoji',
              'assign_content_owner',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'channel_mentions',
              'delete_others_message',
              'create_inner_groups',
              'delete_inner_groups',
              'archive_groups',
              'order_move_group_structure',
              'invite_member',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'crud_series',
              'publish_unpublish_post',
              'cud_tags',
            ],
            '9e37c2e4-dac6-4587-ae95-58c859533ad4': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'ac86538b-8663-4b98-a03e-0ed17ec3f6be': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'bd3eaf59-8103-4d7c-9cc4-f6baae8fca40': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'eacb3c2b-7856-4d7b-bb44-b4c0313eb367': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            'ad0d32cf-c072-41f0-b485-c761d8d75787': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
            ],
            '403a7b9c-dcec-4b28-84f8-f66930a7545a': [
              'crud_post_article',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'crud_uc',
              'manage',
            ],
            'eb25ddf2-1260-40df-b696-a4b785c4c9bd': [
              'crud_post_article',
              'crud_uc',
              'delete_own_message',
              'edit_own_message',
              'send_message',
              'add_member',
              'approve_reject_jr',
              'archive_groups',
              'assign_content_owner',
              'assign_unassign_role',
              'channel_mentions',
              'create_custom_emoji',
              'create_inner_groups',
              'crud_series',
              'delete_inner_groups',
              'delete_others_message',
              'edit_info',
              'edit_join_setting',
              'edit_post_approval_setting',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'edit_privacy',
              'invite_member',
              'order_move_group_structure',
              'publish_unpublish_post',
              'remove_member',
              'cud_tags',
            ],
            '29583a76-2543-4def-95a4-b8e5116b47d6': [
              'crud_post_article',
              'crud_uc',
              'delete_own_message',
              'edit_own_message',
              'send_message',
              'add_member',
              'approve_reject_jr',
              'archive_groups',
              'assign_content_owner',
              'assign_unassign_role',
              'channel_mentions',
              'create_custom_emoji',
              'create_inner_groups',
              'crud_series',
              'delete_inner_groups',
              'delete_others_message',
              'edit_info',
              'edit_join_setting',
              'edit_post_approval_setting',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'edit_privacy',
              'invite_member',
              'order_move_group_structure',
              'publish_unpublish_post',
              'remove_member',
              'cud_tags',
            ],
            '572c8da9-efd4-4179-ae46-f1f15ba18cef': [
              'add_member',
              'approve_reject_jr',
              'assign_unassign_role',
              'channel_mentions',
              'crud_post_article',
              'crud_series',
              'crud_uc',
              'delete_others_message',
              'delete_own_message',
              'edit_info',
              'edit_join_setting',
              'edit_own_message',
              'edit_post_approval_setting',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'edit_privacy',
              'invite_member',
              'publish_unpublish_post',
              'remove_member',
              'send_message',
              'cud_tags',
              'archive_groups',
              'assign_content_owner',
              'create_custom_emoji',
              'create_inner_groups',
              'delete_inner_groups',
              'order_move_group_structure',
            ],
            '3db7a7ab-39a8-42cf-a4d8-e8984d26009e': [
              'invite_member',
              'assign_unassign_role',
              'edit_join_setting',
              'edit_info',
              'edit_privacy',
              'edit_post_approval_setting',
              'crud_series',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'publish_unpublish_post',
              'send_message',
              'edit_own_message',
              'delete_own_message',
              'channel_mentions',
              'delete_others_message',
              'add_member',
              'remove_member',
              'approve_reject_jr',
              'crud_post_article',
              'crud_uc',
              'cud_tags',
              'manage',
            ],
            '2fdbde64-a4e9-440a-a455-18a941ebcf8d': [
              'crud_post_article',
              'crud_uc',
              'delete_own_message',
              'edit_own_message',
              'send_message',
              'add_member',
              'approve_reject_jr',
              'archive_groups',
              'assign_content_owner',
              'assign_unassign_role',
              'channel_mentions',
              'create_custom_emoji',
              'create_inner_groups',
              'crud_series',
              'delete_inner_groups',
              'delete_others_message',
              'edit_info',
              'edit_join_setting',
              'edit_post_approval_setting',
              'edit_post_of_inactive_user',
              'edit_post_setting',
              'edit_privacy',
              'invite_member',
              'order_move_group_structure',
              'publish_unpublish_post',
              'remove_member',
              'cud_tags',
            ],
          },
        },
      };
    } else {
      userInfo = await this._userAppService.findByUserName(user.username, {
        withPermission: true,
      });
    }

    if (!userInfo) {
      throw new LogicException(HTTP_STATUS_ID.API_UNAUTHORIZED);
    }
    return {
      id: userInfo.id,
      avatar: userInfo.avatar,
      email: userInfo.email,
      username: userInfo.username,
      fullname: userInfo.fullname,
      permissions: userInfo.permissions,
      groups: userInfo.groups || [],
    };
  }

  public async login(token: string): Promise<UserDto> {
    const decodedJwt = jwt.decode(token, { complete: true });
    if (!decodedJwt) {
      throw new UnauthorizedException('Unauthorized');
    }

    const cognitoConfig = this._configService.get<ICognitoConfig>('cognito');
    const tokenValidationUrl = `https://cognito-idp.${cognitoConfig.region}.amazonaws.com/${cognitoConfig.poolId}/.well-known/jwks.json`;
    const response = await lastValueFrom(this._httpService.get(tokenValidationUrl));
    const keys = response['data']['keys'];
    const pems = keys
      .map((key) => {
        const keyId = key.kid;
        const modulus = key.n;
        const exponent = key.e;
        const keyType = key.kty;
        const jwk = { kty: keyType, n: modulus, e: exponent };
        return {
          [keyId]: jwkToPem(jwk),
        };
      })
      .reduce((obj, item) => ({ ...obj, ...item }), {});

    const kid = decodedJwt['header']['kid'];
    const pem = pems[kid];
    if (!pem) {
      throw new LogicException(HTTP_STATUS_ID.API_UNAUTHORIZED);
    }
    let payload;

    try {
      payload = await jwt.verify(token, pem);
    } catch (e) {
      if (e instanceof TokenExpiredError) {
        throw new LogicException(HTTP_STATUS_ID.APP_AUTH_TOKEN_EXPIRED);
      }
      throw new LogicException(HTTP_STATUS_ID.API_UNAUTHORIZED);
    }

    if (!payload) {
      throw new LogicException(HTTP_STATUS_ID.API_UNAUTHORIZED);
    }

    return this.getUser(payload);
  }
}
