export const QUIZ_PENDING_PUBLISHER_TOKEN = 'QUIZ_PENDING_PUBLISHER_TOKEN';
export const QUIZ_PARTICIPANT_PUBLISHER_TOKEN = 'QUIZ_PARTICIPANT_PUBLISHER_TOKEN';
export const PUBLISH_REMOVE_CONTENT_PUBLISHER_TOKEN = 'PUBLISH_REMOVE_CONTENT_PUBLISHER_TOKEN';
