export const QUIZ_PENDING_PUBLISHER_TOKEN = 'QUIZ_PENDING_PUBLISHER_TOKEN';
export const QUIZ_PARTICIPANT_PUBLISHER_TOKEN = 'QUIZ_PARTICIPANT_PUBLISHER_TOKEN';
export const PRODUCER_ATTACH_DETACH_PUBLISHER_TOKEN = 'PRODUCER_ATTACH_DETACH_PUBLISHER_TOKEN';
