export const QUIZ_PENDING_PUBLISHER_TOKEN = 'QUIZ_PENDING_PUBLISHER_TOKEN';
export const QUIZ_PARTICIPANT_PUBLISHER_TOKEN = 'QUIZ_PARTICIPANT_PUBLISHER_TOKEN';
export const CONTENT_CHANGED_PUBLISHER_TOKEN = 'CONTENT_CHANGED_PUBLISHER_TOKEN';
