export enum TypeActivity {
  POST = 'POST',
  COMMENT = 'COMMENT',
  ARTICLE = 'ARTICLE',
  SERIES = 'SERIES',
  CHILD_COMMENT = 'CHILD_COMMENT',
  REPORT_CONTENT = 'REPORT_CONTENT',
}

export enum VerbActivity {
  APPROVE_REPORT_CONTENT = 'APPROVE_REPORT_CONTENT',
  POST = 'POST',
  COMMENT = 'COMMENT',
  REACT = 'REACT',
  REPORT = 'REPORT',
}
