export const CONTENT_SCHEDULED_SERVICE_TOKEN = 'CONTENT_SCHEDULED_SERVICE_TOKEN';
export const QUIZ_PENDING_SERVICE_TOKEN = 'QUIZ_PENDING_SERVICE_TOKEN';
export const QUIZ_PARTICIPANT_SERVICE_TOKEN = 'QUIZ_PARTICIPANT_SERVICE_TOKEN';
export const CONTENT_CHANGED_SERVICE_TOKEN = 'CONTENT_CHANGED_SERVICE_TOKEN';
export const FOLLOW_UNFOLLOW_GROUPS_SERVICE_TOKEN = 'FOLLOW_UNFOLLOW_GROUPS_SERVICE_TOKEN';
