export enum QueueName {
  CONTENT_SCHEDULED = 'CONTENT_SCHEDULED',
  QUIZ_PARTICIPANT_RESULT = 'QUIZ_PARTICIPANT_RESULT',
  QUIZ_PENDING = 'QUIZ_PENDING',
  PRODUCER_ATTACH_DETACH_NEWSFEED = 'PRODUCER_ATTACH_DETACH_NEWSFEED',
  ATTACH_DETACH_NEWSFEED = 'ATTACH_DETACH_NEWSFEED',
  FOLLOW_UNFOLLOW_GROUPS = 'FOLLOW_UNFOLLOW_GROUPS',
  PRODUCER_FOLLOW_UNFOLLOW_GROUPS = 'PRODUCER_FOLLOW_UNFOLLOW_GROUPS',
}

export enum QueueGroup {
  QUIZ_PENDING_GROUP = 'QUIZ_PENDING_GROUP',
}
