export enum QueueName {
  CONTENT_SCHEDULED = 'CONTENT_SCHEDULED',
  QUIZ_PARTICIPANT_RESULT = 'QUIZ_PARTICIPANT_RESULT',
  QUIZ_PENDING = 'QUIZ_PENDING',
  CONTENT_CHANGED = 'CONTENT_CHANGED',
  FOLLOW_UNFOLLOW_GROUPS = 'FOLLOW_UNFOLLOW_GROUPS',
}

export enum QueueGroup {
  QUIZ_PENDING_GROUP = 'QUIZ_PENDING_GROUP',
}
