export const REDIS_STORE_INSTANCE_TOKEN = 'REDIS_STORE_INSTANCE_TOKEN';
export const REDIS_CONTENT_INSTANCE_TOKEN = 'REDIS_CONTENT_INSTANCE_TOKEN';
export const REDIS_STORE_MODULE_ID = 'REDIS_STORE_MODULE_ID';
export const REDIS_STORE_MODULE_OPTIONS = 'REDIS_STORE_MODULE_OPTIONS';
