export const QUIZ_PENDING_PROCESSOR_TOKEN = 'QUIZ_PENDING_PROCESSOR_TOKEN';
export const CONTENT_SCHEDULED_PROCESSOR_TOKEN = 'CONTENT_SCHEDULED_PROCESSOR_TOKEN';
export const QUIZ_PARTICIPANT_PROCESSOR_TOKEN = 'QUIZ_PARTICIPANT_PROCESSOR_TOKEN';
export const CONTENT_CHANGED_PROCESSOR_TOKEN = 'CONTENT_CHANGED_PROCESSOR_TOKEN';
export const FOLLOW_UNFOLLOW_GROUPS_PROCESSOR_TOKEN = 'FOLLOW_UNFOLLOW_GROUPS_PROCESSOR_TOKEN';
