export enum WS_ACTIVITY_VERB {
  POST = 'POST',
  COMMENT = 'COMMENT',
  REACT = 'REACT',
  GENERATE_QUIZ = 'GENERATE_QUIZ',
}

export enum WS_TARGET_TYPE {
  POST = 'POST',
  ARTICLE = 'ARTICLE',
  SERIES = 'SERIES',
  COMMENT = 'COMMENT',
  QUIZ = 'QUIZ',
}
