/*
 * Queue publisher service
 */
export const CONTENT_SCHEDULED_PUBLISHER_TOKEN = 'CONTENT_SCHEDULED_PUBLISHER_TOKEN';
export const FOLLOW_UNFOLLOW_GROUPS_PUBLISHER_TOKEN = 'FOLLOW_UNFOLLOW_GROUPS_PUBLISHER_TOKEN';
