export const CONTENT_SCHEDULED_WORKER_TOKEN = 'CONTENT_SCHEDULED_WORKER_TOKEN';
export const QUIZ_PENDING_WORKER_TOKEN = 'QUIZ_PENDING_WORKER_TOKEN';
export const QUIZ_PARTICIPANT_WORKER_TOKEN = 'QUIZ_PARTICIPANT_WORKER_TOKEN';
