export const CONTENT_SCHEDULED_TOKEN = 'CONTENT_SCHEDULED_TOKEN';
export const CONTENT_SCHEDULED_SERVICE_TOKEN = 'CONTENT_SCHEDULED_SERVICE_TOKEN';

export const QUEUE_ADAPTER_SERVICES = [CONTENT_SCHEDULED_SERVICE_TOKEN];
