export const QUEUE_POSTFIX = '_TOKEN';
export const QUEUE_ADAPTER_POSTFIX = '_SERVICE_TOKEN';

export const CONTENT_SCHEDULED_TOKEN = 'CONTENT_SCHEDULED_TOKEN';
export const CONTENT_SCHEDULED_SERVICE_TOKEN = 'CONTENT_SCHEDULED_SERVICE_TOKEN';

export const QUEUE_ADAPTER_SERVICES = [CONTENT_SCHEDULED_SERVICE_TOKEN];
