name: develop
run-name: ${{ github.ref_name }}
on:
  pull_request:
    types:
      - closed
    branches: ["develop"]
    paths-ignore:
      - 'serverless/**'
      - '.github/workflows/*-serverless.yml'

permissions:
  contents: read    # This is required for actions/checkout
  id-token: write   # This is required for requesting the JWT
  pull-requests: read # This is required for action dorny/paths-filter@v2

jobs:
  develop:
    if: ${{ github.ref_name == 'develop' }}
    runs-on: ubuntu-22.04
    outputs:
      api: ${{ steps.filter.outputs.api }}
      worker: ${{ steps.filter.outputs.worker }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        # Specify the base branch to compare against
        base: 'develop'
        filters: |
          api:
            - 'apps/api/**'
          worker:
            - 'apps/worker/**'

  build_service_api:
    needs: develop
    if:  ${{ !cancelled() }}
    # if:  ${{ !cancelled() && needs.develop.outputs.api == 'true' }}
    runs-on: ubuntu-22.04
    environment: develop
    env:
      AWS_SM_SECRET_ID: /bic/ci
      AWS_IAM_ROLE: arn:aws:iam::210668178631:role/bic-all-github-action-iam-role
      BITBUCKET_WORKPLACE: beincomm
      GITHUB_WORKPLACE: beincom
      ENVIRONMENT: dev
      SERVICE: content
      MICROSERVICE: api
      IMAGE_NAME_API: beingroup/dev-bic-content-api-microservice
      IMAGE_NAME_WORKER: beingroup/dev-bic-content-worker-microservice

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials with IAM Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.AWS_IAM_ROLE }}
        aws-region: ap-southeast-1

    - name: Get Secrets from AWS Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          ${{ env.AWS_SM_SECRET_ID }}
        parse-json-secrets: true

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env._BIC_CI_NON_PRO_DOCKERHUB_USERNAME }}
        password: ${{ env._BIC_CI_NON_PRO_DOCKERHUB_PASSWORD }}

    - name: Build then Push Docker Image to DockerHub
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./apps/api/Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME_API }}:latest,${{ env.IMAGE_NAME_API }}:${{ github.sha }}

    - name: Install Envsubst
      run: sudo apt-get update && sudo apt-get -y install gettext-base

    - name: Update Image Version to GitOps Repository
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 5
        retry_wait_seconds: 20
        on_retry_command: rm -rf bic-kube
        command: |
          HEAD=$(git rev-parse --short HEAD)
          git clone https://devops-bic:${{ env._BIC_CI_ARGOCD_TOKEN_GITHUB }}@github.com/${{ env.GITHUB_WORKPLACE }}/bic-kube.git
          cd bic-kube
          set -e
          export COMMIT_SHA1=${{ github.sha }}
          envsubst <bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/${{ env.MICROSERVICE }}/version.patch.yaml >bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/${{ env.MICROSERVICE }}/version.yaml.out
          mv bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/${{ env.MICROSERVICE }}/version.yaml.out bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/${{ env.MICROSERVICE }}/version.yaml
          git config --global user.email "devops@evol.vn"
          git config --global user.name "devops-bic"
          git add -A
          git commit -m "Commit: $HEAD  Build: ${{ github.run_number }}"
          git pull
          git fetch
          git push

  build_service_worker:
    needs: [develop, build_service_api]
    if:  ${{ !cancelled() }}
    # if:  ${{ !cancelled() && needs.develop.outputs.worker == 'true' }}
    runs-on: ubuntu-22.04
    environment: develop
    env:
      AWS_SM_SECRET_ID: /bic/ci
      AWS_IAM_ROLE: arn:aws:iam::210668178631:role/bic-all-github-action-iam-role
      BITBUCKET_WORKPLACE: beincomm
      GITHUB_WORKPLACE: beincom
      ENVIRONMENT: dev
      SERVICE: content
      MICROSERVICE: worker
      IMAGE_NAME_API: beingroup/dev-bic-content-api-microservice
      IMAGE_NAME_WORKER: beingroup/dev-bic-content-worker-microservice

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials with IAM Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.AWS_IAM_ROLE }}
        aws-region: ap-southeast-1

    - name: Get Secrets from AWS Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          ${{ env.AWS_SM_SECRET_ID }}
        parse-json-secrets: true

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env._BIC_CI_NON_PRO_DOCKERHUB_USERNAME }}
        password: ${{ env._BIC_CI_NON_PRO_DOCKERHUB_PASSWORD }}

    - name: Build then Push Docker Image to DockerHub
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./apps/worker/Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME_WORKER }}:latest,${{ env.IMAGE_NAME_WORKER }}:${{ github.sha }}

    - name: Install Envsubst
      run: sudo apt-get update && sudo apt-get -y install gettext-base

    - name: Update Image Version to GitOps Repository
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 5
        retry_wait_seconds: 20
        on_retry_command: rm -rf bic-kube
        command: |
          HEAD=$(git rev-parse --short HEAD)
          git clone https://devops-bic:${{ env._BIC_CI_ARGOCD_TOKEN_GITHUB }}@github.com/${{ env.GITHUB_WORKPLACE }}/bic-kube.git
          cd bic-kube
          set -e
          export COMMIT_SHA1=${{ github.sha }}
          envsubst <bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/${{ env.MICROSERVICE }}/version.patch.yaml >bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/${{ env.MICROSERVICE }}/version.yaml.out
          mv bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/${{ env.MICROSERVICE }}/version.yaml.out bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/${{ env.MICROSERVICE }}/version.yaml
          git config --global user.email "devops@evol.vn"
          git config --global user.name "devops-bic"
          git add -A
          git commit -m "Commit: $HEAD  Build: ${{ github.run_number }}"
          git pull
          git fetch
          git push

  build_service_feed:
    if: ${{ github.ref_name == 'develop' }}
    runs-on: ubuntu-22.04
    environment: develop
    env:
      AWS_SM_SECRET_ID: /bic/ci
      AWS_IAM_ROLE: arn:aws:iam::210668178631:role/bic-all-github-action-iam-role
      BITBUCKET_WORKPLACE: beincomm
      GITHUB_WORKPLACE: beincom
      ENVIRONMENT: dev
      SERVICE: feed
      IMAGE_NAME: beingroup/dev-bic-feed-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials with IAM Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.AWS_IAM_ROLE }}
        aws-region: ap-southeast-1

    - name: Get Secrets from AWS Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          ${{ env.AWS_SM_SECRET_ID }}
        parse-json-secrets: true

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env._BIC_CI_NON_PRO_DOCKERHUB_USERNAME }}
        password: ${{ env._BIC_CI_NON_PRO_DOCKERHUB_PASSWORD }}

    - name: Build then Push Docker Image to DockerHub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ github.sha }}
      
    - name: Install Envsubst
      run: sudo apt-get update && sudo apt-get -y install gettext-base

    - name: Update Image Version to GitOps Repository
      run: |
        HEAD=$(git rev-parse --short HEAD)
        git clone https://devops-bic:${{ env._BIC_CI_ARGOCD_TOKEN_GITHUB }}@github.com/${{ env.GITHUB_WORKPLACE }}/bic-kube.git
        cd bic-kube
        set -e
        export COMMIT_SHA1=${{ github.sha }}
        envsubst <bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/version.patch.yaml >bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/version.yaml.out
        mv bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/version.yaml.out bic/services/${{ env.SERVICE }}/${{ env.ENVIRONMENT }}/version.yaml
        git config --global user.email "devops@evol.vn"
        git config --global user.name "devops-bic"
        git add -A
        git commit -m "Commit: $HEAD  Build: ${{ github.run_number }}"
        git pull
        git push
