name: quality-control
run-name: ${{ github.actor }} just push/merge code
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.1'
      - name: Cache/Restore node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependency packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Run unit test
        run: npx jest --coverage
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/lcov.info
